import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-app-store-commission-tax-settlement",
  "engine": "recovery",
  "title": "App Store Commission & Tax Settlement",
  "shortTitle": "App Store Commission and Tax Settlement",
  "tagline": "Quantify, recover, and prevent financial leakage through app store commission & tax settlement",
  "industry": "Digital Publisher Revenue Assurance",
  "uiPort": 4629,
  "apiPort": 5629,
  "accent": "#c2410c",
  "currency": "USD",
  "primaryOutcome": "App Store Commission & Tax Settlement converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect developer agreements, applications, SKUs, transactions, subscriptions, store commissions, rate programs, in-app purchases, refunds, chargebacks, territory taxes, withholding, currency, and payouts in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "paidSettlement",
    "expectedKey": "expectedSettlement",
    "actualLabel": "Store Paid Settlement",
    "expectedLabel": "Calculated Publisher Revenue",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "App Store Commission & Tax Settlement evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("store-developer-agreement-library","ASC01","Store developer agreement library","Execute store developer agreement library using developer agreements, applications, SKUs, transactions, subscriptions, store commissions, rate programs, in-app purchases, refunds, chargebacks, territory taxes, withholding, currency, and payouts.","Produce a governed store developer agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Store / Application","text","Store / Application · Standard Case"],["caseReference","Store developer agreement library Reference","text","ASC01-2026-001"],["paidSettlement","Store Paid Settlement","currency",1123000],["expectedSettlement","Calculated Publisher Revenue","currency",1325140],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Store developer agreement library case","Application SKU registry case","Transaction ingestion case","Subscription ingestion case","Store commission calculation case"]}),
feature("application-sku-registry","ASC02","Application SKU registry","Execute application sku registry using developer agreements, applications, SKUs, transactions, subscriptions, store commissions, rate programs, in-app purchases, refunds, chargebacks, territory taxes, withholding, currency, and payouts.","Produce a governed application sku registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Store / Application","text","Store / Application · Standard Case"],["caseReference","Application SKU registry Reference","text","ASC02-2026-001"],["paidSettlement","Store Paid Settlement","currency",1123000],["expectedSettlement","Calculated Publisher Revenue","currency",1325140],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Store developer agreement library case","Application SKU registry case","Transaction ingestion case","Subscription ingestion case","Store commission calculation case"]}),
feature("transaction-ingestion","ASC03","Transaction ingestion","Execute transaction ingestion using developer agreements, applications, SKUs, transactions, subscriptions, store commissions, rate programs, in-app purchases, refunds, chargebacks, territory taxes, withholding, currency, and payouts.","Produce a governed transaction ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Store / Application","text","Store / Application · Standard Case"],["caseReference","Transaction ingestion Reference","text","ASC03-2026-001"],["paidSettlement","Store Paid Settlement","currency",1123000],["expectedSettlement","Calculated Publisher Revenue","currency",1325140],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Store developer agreement library case","Application SKU registry case","Transaction ingestion case","Subscription ingestion case","Store commission calculation case"]}),
feature("subscription-ingestion","ASC04","Subscription ingestion","Execute subscription ingestion using developer agreements, applications, SKUs, transactions, subscriptions, store commissions, rate programs, in-app purchases, refunds, chargebacks, territory taxes, withholding, currency, and payouts.","Produce a governed subscription ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Store / Application","text","Store / Application · Standard Case"],["caseReference","Subscription ingestion Reference","text","ASC04-2026-001"],["paidSettlement","Store Paid Settlement","currency",1123000],["expectedSettlement","Calculated Publisher Revenue","currency",1325140],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Store developer agreement library case","Application SKU registry case","Transaction ingestion case","Subscription ingestion case","Store commission calculation case"]}),
feature("store-commission-calculation","ASC05","Store commission calculation","Execute store commission calculation using developer agreements, applications, SKUs, transactions, subscriptions, store commissions, rate programs, in-app purchases, refunds, chargebacks, territory taxes, withholding, currency, and payouts.","Produce a governed store commission calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Store / Application","text","Store / Application · Standard Case"],["caseReference","Store commission calculation Reference","text","ASC05-2026-001"],["paidSettlement","Store Paid Settlement","currency",1123000],["expectedSettlement","Calculated Publisher Revenue","currency",1325140],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Store developer agreement library case","Application SKU registry case","Transaction ingestion case","Subscription ingestion case","Store commission calculation case"]}),
feature("small-business-rate-validation","ASC06","Small-business rate validation","Execute small-business rate validation using developer agreements, applications, SKUs, transactions, subscriptions, store commissions, rate programs, in-app purchases, refunds, chargebacks, territory taxes, withholding, currency, and payouts.","Produce a governed small-business rate validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Store / Application","text","Store / Application · Standard Case"],["caseReference","Small-business rate validation Reference","text","ASC06-2026-001"],["paidSettlement","Store Paid Settlement","currency",1123000],["expectedSettlement","Calculated Publisher Revenue","currency",1325140],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Store developer agreement library case","Application SKU registry case","Transaction ingestion case","Subscription ingestion case","Store commission calculation case"]}),
feature("subscription-rate-transition","ASC07","Subscription rate transition","Execute subscription rate transition using developer agreements, applications, SKUs, transactions, subscriptions, store commissions, rate programs, in-app purchases, refunds, chargebacks, territory taxes, withholding, currency, and payouts.","Produce a governed subscription rate transition decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Store / Application","text","Store / Application · Standard Case"],["caseReference","Subscription rate transition Reference","text","ASC07-2026-001"],["paidSettlement","Store Paid Settlement","currency",1123000],["expectedSettlement","Calculated Publisher Revenue","currency",1325140],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Store developer agreement library case","Application SKU registry case","Transaction ingestion case","Subscription ingestion case","Store commission calculation case"]}),
feature("in-app-purchase-reconciliation","ASC08","In-app purchase reconciliation","Execute in-app purchase reconciliation using developer agreements, applications, SKUs, transactions, subscriptions, store commissions, rate programs, in-app purchases, refunds, chargebacks, territory taxes, withholding, currency, and payouts.","Produce a governed in-app purchase reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Store / Application","text","Store / Application · Standard Case"],["caseReference","In-app purchase reconciliation Reference","text","ASC08-2026-001"],["paidSettlement","Store Paid Settlement","currency",1123000],["expectedSettlement","Calculated Publisher Revenue","currency",1325140],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Store developer agreement library case","Application SKU registry case","Transaction ingestion case","Subscription ingestion case","Store commission calculation case"]}),
feature("refund-chargeback-audit","ASC09","Refund chargeback audit","Execute refund chargeback audit using developer agreements, applications, SKUs, transactions, subscriptions, store commissions, rate programs, in-app purchases, refunds, chargebacks, territory taxes, withholding, currency, and payouts.","Produce a governed refund chargeback audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Store / Application","text","Store / Application · Standard Case"],["caseReference","Refund chargeback audit Reference","text","ASC09-2026-001"],["paidSettlement","Store Paid Settlement","currency",1123000],["expectedSettlement","Calculated Publisher Revenue","currency",1325140],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Store developer agreement library case","Application SKU registry case","Transaction ingestion case","Subscription ingestion case","Store commission calculation case"]}),
feature("territory-tax-treatment","ASC10","Territory tax treatment","Execute territory tax treatment using developer agreements, applications, SKUs, transactions, subscriptions, store commissions, rate programs, in-app purchases, refunds, chargebacks, territory taxes, withholding, currency, and payouts.","Produce a governed territory tax treatment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Store / Application","text","Store / Application · Standard Case"],["caseReference","Territory tax treatment Reference","text","ASC10-2026-001"],["paidSettlement","Store Paid Settlement","currency",1123000],["expectedSettlement","Calculated Publisher Revenue","currency",1325140],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Store developer agreement library case","Application SKU registry case","Transaction ingestion case","Subscription ingestion case","Store commission calculation case"]}),
feature("withholding-calculation","ASC11","Withholding calculation","Execute withholding calculation using developer agreements, applications, SKUs, transactions, subscriptions, store commissions, rate programs, in-app purchases, refunds, chargebacks, territory taxes, withholding, currency, and payouts.","Produce a governed withholding calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Store / Application","text","Store / Application · Standard Case"],["caseReference","Withholding calculation Reference","text","ASC11-2026-001"],["paidSettlement","Store Paid Settlement","currency",1123000],["expectedSettlement","Calculated Publisher Revenue","currency",1325140],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Store developer agreement library case","Application SKU registry case","Transaction ingestion case","Subscription ingestion case","Store commission calculation case"]}),
feature("currency-conversion","ASC12","Currency conversion","Execute currency conversion using developer agreements, applications, SKUs, transactions, subscriptions, store commissions, rate programs, in-app purchases, refunds, chargebacks, territory taxes, withholding, currency, and payouts.","Produce a governed currency conversion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Store / Application","text","Store / Application · Standard Case"],["caseReference","Currency conversion Reference","text","ASC12-2026-001"],["paidSettlement","Store Paid Settlement","currency",1123000],["expectedSettlement","Calculated Publisher Revenue","currency",1325140],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Store developer agreement library case","Application SKU registry case","Transaction ingestion case","Subscription ingestion case","Store commission calculation case"]}),
feature("store-statement-matching","ASC13","Store statement matching","Execute store statement matching using developer agreements, applications, SKUs, transactions, subscriptions, store commissions, rate programs, in-app purchases, refunds, chargebacks, territory taxes, withholding, currency, and payouts.","Produce a governed store statement matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Store / Application","text","Store / Application · Standard Case"],["caseReference","Store statement matching Reference","text","ASC13-2026-001"],["paidSettlement","Store Paid Settlement","currency",1123000],["expectedSettlement","Calculated Publisher Revenue","currency",1325140],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Store developer agreement library case","Application SKU registry case","Transaction ingestion case","Subscription ingestion case","Store commission calculation case"]}),
feature("missing-payout-detection","ASC14","Missing payout detection","Execute missing payout detection using developer agreements, applications, SKUs, transactions, subscriptions, store commissions, rate programs, in-app purchases, refunds, chargebacks, territory taxes, withholding, currency, and payouts.","Produce a governed missing payout detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Store / Application","text","Store / Application · Standard Case"],["caseReference","Missing payout detection Reference","text","ASC14-2026-001"],["paidSettlement","Store Paid Settlement","currency",1123000],["expectedSettlement","Calculated Publisher Revenue","currency",1325140],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Store developer agreement library case","Application SKU registry case","Transaction ingestion case","Subscription ingestion case","Store commission calculation case"]}),
feature("app-territory-analytics","ASC15","App territory analytics","Execute app territory analytics using developer agreements, applications, SKUs, transactions, subscriptions, store commissions, rate programs, in-app purchases, refunds, chargebacks, territory taxes, withholding, currency, and payouts.","Produce a governed app territory analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Store / Application","text","Store / Application · Standard Case"],["caseReference","App territory analytics Reference","text","ASC15-2026-001"],["paidSettlement","Store Paid Settlement","currency",1123000],["expectedSettlement","Calculated Publisher Revenue","currency",1325140],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidSettlement",subjects:["Store developer agreement library case","Application SKU registry case","Transaction ingestion case","Subscription ingestion case","Store commission calculation case"]})
]);
